experiment:
  name: "housing_regression_experiment"
  tracking_uri: "sqlite:///metadata/mlflow/mlruns.db"
  artifact_location: "./metadata/mlflow/mlartifacts"

# Set the registry server URI. This property is especially useful if you have a registry
# server that’s different from the tracking server.
# model_registry:
#   uri: sqlite:////tmp/registry.db

# Use a small sample from the TLC Trip Record Dataset for exploring the MLflow Regression Pipeline
# (https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page)
# INGEST_DATA_LOCATION: "./data/sample.parquet"
INGEST_DATA_LOCATION: "data/housing.csv"

INGEST_DATA_FORMAT: csv

INGEST_SCORING_DATA_LOCATION: "./data/housing.parquet"

INGEST_SCORING_DATA_FORMAT: parquet
SPLIT_RATIOS: [0.80, 0.10, 0.10]
SCORED_OUTPUT_DATA_LOCATION: "./data/housing_output.parquet"
SCORED_OUTPUT_DATA_FORMAT: parquet