version: "3"

services:
  jupyter:
    image: dlenv_local
    ports:
      - 8888:8888
    volumes:
      - ./scripts:/home/workspace/scripts
    command: jupyter-lab --allow-root --no-browser --ip=0.0.0.0 --NotebookApp.token='' --NotebookApp.password=''


  mlflow:
    image: mlflow_local
    ports:
      - 5000:5000
    volumes:
      - ./scripts/mlruns:/home/workspace/mlruns
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlruns.db --default-artifact-root .


  # gitlab:
  #   image:
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - gitlab/repository_data:/home/workspace/gitlab/data
